springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PETSTOREORDERSERVICE_SERVER_PORT:8080}

petstore:
  service:
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}
  cosmo:
    database:
      url: ${PETSTOREPRODUCTCOSMODB_URL}
      key: ${PETSTOREPRODUCTCOSMODB_KEY}
  servicebus:
    connection-string: ${PETSTORESERVICEBUS}
    queue-name: ${PETSTOREQUEUENAME}
spring:
  application:
    name: petstoreorderservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
